# Generated by Django 4.1.5 on 2023-01-31 21:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('baseball', '0002_atbat_game_league_lineup_player_season_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='teams',
        ),
        migrations.AddField(
            model_name='game',
            name='away_team',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='away_games', to='baseball.team'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='game',
            name='home_team',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='home_games', to='baseball.team'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='team',
            name='location',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='stadium',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
