# Generated by Django 4.1.5 on 2023-01-31 21:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('baseball', '0003_remove_game_teams_game_away_team_game_home_team_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RunnersLeftOn',
            new_name='LeftOnRunner',
        ),
        migrations.RenameField(
            model_name='atbat',
            old_name='runners_left_on',
            new_name='left_on_runners',
        ),
    ]
