# Generated by Django 4.1.5 on 2023-02-01 02:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('baseball', '0005_scheduledgame'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='atbat',
            name='left_on_runners',
        ),
        migrations.RemoveField(
            model_name='leftonrunner',
            name='at_bat',
        ),
        migrations.AddField(
            model_name='leftonrunner',
            name='at_bat',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.RESTRICT, to='baseball.atbat'),
            preserve_default=False,
        ),
    ]
