# Generated by Django 4.1.5 on 2023-02-01 05:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('baseball', '0009_alter_player_team'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PlayerAttribute',
        ),
    ]
