# Generated by Django 4.1.5 on 2023-02-01 05:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('baseball', '0010_delete_playerattribute'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('composure', models.IntegerField()),
                ('endurance', models.IntegerField()),
                ('intellect', models.IntegerField()),
                ('reflexes', models.IntegerField()),
                ('speed', models.IntegerField()),
                ('strength', models.IntegerField()),
                ('willpower', models.IntegerField()),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='baseball.player')),
            ],
        ),
    ]
