# Generated by Django 4.1.5 on 2023-02-01 05:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('baseball', '0011_playerattribute'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playerattribute',
            name='id',
        ),
        migrations.AlterField(
            model_name='playerattribute',
            name='player',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='baseball.player'),
        ),
    ]
