# Generated by Django 4.1.5 on 2023-02-01 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseball', '0012_remove_playerattribute_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
