# Generated by Django 4.1.5 on 2023-02-02 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseball', '0015_alter_team_location_alter_team_stadium'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='games',
            field=models.ManyToManyField(blank=True, to='baseball.game'),
        ),
    ]
