# Generated by Django 4.1.5 on 2023-02-06 00:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('baseball', '0017_alter_team_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ScheduledGame',
        ),
    ]
