# Generated by Django 4.1.5 on 2023-02-07 01:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('baseball', '0018_delete_scheduledgame'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playerattribute',
            name='player',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='attributes', serialize=False, to='baseball.player'),
        ),
    ]
