# Generated by Django 4.1.5 on 2023-02-07 02:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('baseball', '0019_alter_playerattribute_player'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='atbat',
            name='player',
        ),
        migrations.AddField(
            model_name='atbat',
            name='batter',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, related_name='batted_at_bats', to='baseball.player'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='atbat',
            name='pitcher',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, related_name='pitched_at_bats', to='baseball.player'),
            preserve_default=False,
        ),
    ]
