# Generated by Django 4.1.5 on 2023-02-07 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseball', '0020_remove_atbat_player_atbat_batter_atbat_pitcher'),
    ]

    operations = [
        migrations.AddField(
            model_name='atbat',
            name='game_at_bat_number',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
