# Generated by Django 4.1.6 on 2023-02-28 01:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('baseball', '0022_alter_leftonrunner_at_bat'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='game',
            options={'ordering': ['date']},
        ),
    ]
