# Generated by Django 4.1.6 on 2023-02-28 02:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('baseball', '0023_alter_game_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='game',
            options={'ordering': ['-date']},
        ),
    ]
