# Generated by Django 4.1.6 on 2023-02-28 03:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('baseball', '0024_alter_game_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='game',
            options={'ordering': ['-date_time']},
        ),
        migrations.RenameField(
            model_name='game',
            old_name='date',
            new_name='date_time',
        ),
    ]
