# Generated by Django 4.1.6 on 2023-02-28 04:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('baseball', '0025_alter_game_options_rename_date_game_date_time'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='game',
            options={},
        ),
    ]
