# Generated by Django 4.1.6 on 2023-03-06 13:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('baseball', '0026_alter_game_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atbat',
            name='batter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batted_at_bats', to='baseball.player'),
        ),
        migrations.AlterField(
            model_name='atbat',
            name='pitcher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pitched_at_bats', to='baseball.player'),
        ),
        migrations.AlterField(
            model_name='leftonrunner',
            name='at_bat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runners_left_on_base', to='baseball.atbat'),
        ),
    ]
