# Generated by Django 4.1.6 on 2023-03-06 04:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('baseball', '0026_alter_game_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='atbat',
            name='inning',
        ),
        migrations.CreateModel(
            name='HalfInning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inning', models.IntegerField()),
                ('home_team_at_bat', models.BooleanField()),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='half_innings', to='baseball.game')),
            ],
        ),
        migrations.AddField(
            model_name='atbat',
            name='half_inning',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='at_bats', to='baseball.halfinning'),
            preserve_default=False,
        ),
    ]
