# Generated by Django 4.1.6 on 2023-03-07 00:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('baseball', '0027_alter_atbat_batter_alter_atbat_pitcher_and_more'),
        ('baseball', '0027_remove_atbat_inning_halfinning_atbat_half_inning'),
    ]

    operations = [
    ]
