# Generated by Django 4.1.6 on 2023-03-07 00:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('baseball', '0028_merge_20230307_0029'),
    ]

    operations = [
        migrations.AddField(
            model_name='atbat',
            name='errors',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='atbat',
            name='batter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='batted_at_bats', to='baseball.player'),
        ),
        migrations.AlterField(
            model_name='atbat',
            name='pitcher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='pitched_at_bats', to='baseball.player'),
        ),
    ]
