# Generated by Django 4.1.6 on 2023-04-07 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseball', '0030_manager_user_alter_manager_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manager',
            name='first_name',
            field=models.CharField(blank=True, default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='manager',
            name='last_name',
            field=models.CharField(blank=True, default='', max_length=50),
            preserve_default=False,
        ),
    ]
