# Generated by Django 4.1.6 on 2023-07-18 01:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('baseball', '0032_atbat_lineup_batter_atbat_lineup_pitcher'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='atbat',
            name='batter',
        ),
        migrations.RemoveField(
            model_name='atbat',
            name='pitcher',
        ),
    ]
