# Generated by Django 4.1.6 on 2023-07-18 01:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('baseball', '0033_remove_atbat_batter_remove_atbat_pitcher'),
    ]

    operations = [
        migrations.RenameField(
            model_name='atbat',
            old_name='lineup_batter',
            new_name='batter',
        ),
        migrations.RenameField(
            model_name='atbat',
            old_name='lineup_pitcher',
            new_name='pitcher',
        ),
    ]
