# Generated by Django 4.1.6 on 2023-07-19 01:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('baseball', '0034_rename_lineup_batter_atbat_batter_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='games',
        ),
    ]
